server:
  port: 8090
spring:
  resources:
    static-locations: classpath:/static/, classpath:/templates/
#  thymeleaf:
#    suffix: .html
#    prefix: classpath:/templates/files/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.200.125.114:3306/zzh?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      userName: root
    password: wanan650711
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zyf.graduation.gkwbserver.bean.model


